# Generated by Django 6.0.4 on 2026-04-19 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_hash', models.CharField(blank=True, default='', max_length=64)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.major')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.major')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('classroom', models.CharField(blank=True, default='', max_length=100)),
                ('results_available', models.BooleanField(default=False)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.schoolclass')),
            ],
        ),
    ]
